name: interop tests
on:
  workflow_call:
    inputs:
      client:
        description: "client"
        required: true
        type: string
      servers:
        description: "servers"
        required: true
        type: string

jobs:
  tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        server: ${{ fromJson(inputs.servers) }}
    name: (${{ inputs.client }} - ${{ matrix.server }})
    steps:
      - uses: actions/checkout@v5
      # Remove this when GitHub runner gets docker engine >= v28.1.0.
      - uses: docker/setup-docker-action@v4
        with:
          version: version=v28.3.0
      - uses: actions/setup-python@v6
        with:
          python-version: 3.8
      - name: Enable IPv6 support
        run: sudo modprobe ip6table_filter
      - run: docker image ls
      - name: Download quic-network-simulator image
        uses: actions/download-artifact@v5
        with:
          name: images-quic-network-simulator
      - name: Download quic-interop-iperf-endpoint image
        uses: actions/download-artifact@v5
        with:
          name: images-quic-interop-iperf-endpoint
      - name: Download ${{ matrix.server }} Docker image
        uses: actions/download-artifact@v5
        with:
          name: image-${{ matrix.server }}
      - name: Download ${{ inputs.client }} Docker image
        if: ${{ matrix.server != inputs.client }}
        uses: actions/download-artifact@v5
        with:
          name: image-${{ inputs.client }}
      - name: Load docker images
        run: |
          docker load --input quic-network-simulator.tar.gz
          docker load --input quic-interop-iperf-endpoint.tar.gz
          docker load --input ${{ matrix.server }}.tar.gz
          docker load --input ${{ inputs.client }}.tar.gz
      - run: docker image ls
      - name: Install Wireshark
        run: |
          sudo add-apt-repository ppa:wireshark-dev/nightly
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends tshark
      - name: Install Linux QUIC module
        if: ${{ matrix.server == 'linuxquic' || inputs.client == 'linuxquic' }}
        run: |
          git clone https://github.com/lxin/quic.git
          cd quic && sed -i '/LIBGNUTLS/d' configure.ac
          ./autogen.sh && ./configure --prefix=/usr
          sudo make -C modules install
          cd ../ && rm -r quic
      - name: Install Python packages
        run: |
          pip install -U pip
          pip install -r requirements.txt
      - name: Run tests
        env:
          CRON: "true"
        run: |
          (python run.py --client ${{ inputs.client }} --server ${{ matrix.server }} --log-dir logs --json ${{ matrix.server }}_${{ inputs.client }}_results.json -t onlyTests || true) | tee output.txt
          mkdir -p logs/${{ matrix.server }}_${{ inputs.client }}
          mv output.txt logs/${{ matrix.server }}_${{ inputs.client }}/
      - name: Run measurements
        env:
          CRON: "true"
        run: |
          python run.py --client ${{ inputs.client }} --server ${{ matrix.server }} --log-dir logs_measurement --json ${{ matrix.server }}_${{ inputs.client }}_measurements.json -t onlyMeasurements || true
          if [ ! -d "logs_measurement" ]; then exit 0; fi
          find logs_measurement -depth -name "sim" -type d -exec rm -r "{}" \;
          find logs_measurement -depth -name "client" -type d -exec rm -r "{}" \;
          find logs_measurement -depth -name "server" -type d -exec rm -r "{}" \;
          mv logs_measurement/${{ matrix.server }}_${{ inputs.client }}/* logs/${{ matrix.server }}_${{ inputs.client }}/
      - name: Upload logs to interop.seemann.io
        uses: burnett01/rsync-deployments@33214bd98ba4ac2be90f5976672b3f030fce9ce4 # v7.1.0
        if: ${{ github.event_name == 'schedule' }}
        with:
          switches: -avzr --relative
          path: logs/./${{ matrix.server }}_${{ inputs.client }}/
          remote_path: ${{ vars.LOG_DIR }}/${{ needs.config.outputs.logname }}
          remote_host: interop.seemann.io
          remote_user: ${{ secrets.INTEROP_SEEMANN_IO_USER }}
          remote_key: ${{ secrets.INTEROP_SEEMANN_IO_SSH_KEY }}
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.server }}-${{ inputs.client }}
          if-no-files-found: error
          path: |
            ${{ matrix.server }}_${{ inputs.client }}_results.json
            ${{ matrix.server }}_${{ inputs.client }}_measurements.json
