name: Run Interop Tests
on:
  workflow_call:
    inputs:
      logname:
        required: true
        type: string
      server:
        required: true
        type: string
      clients:
        required: true
        type: string
      

jobs:
  test-clients:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        client: ${{ fromJson(inputs.clients) }}
    name: "client: ${{ matrix.client }}"
    steps:
      - uses: actions/checkout@v6
      # Remove this when GitHub runner gets docker engine >= v28.1.0.
      - uses: docker/setup-docker-action@v4
        with:
          version: version=v28.3.0
      - uses: actions/setup-python@v6
        with:
          python-version: 3.8
      - name: Enable IPv6 support
        run: sudo modprobe ip6table_filter
      - run: docker image ls
      - name: Download quic-network-simulator image
        uses: actions/download-artifact@v7
        with:
          name: images-quic-network-simulator
      - name: Download quic-interop-iperf-endpoint image
        uses: actions/download-artifact@v7
        with:
          name: images-quic-interop-iperf-endpoint
      - name: Download ${{ inputs.server }} Docker image
        uses: actions/download-artifact@v7
        with:
          name: image-${{ inputs.server }}
      - name: Download ${{ matrix.client }} Docker image
        if: ${{ inputs.server != matrix.client }}
        uses: actions/download-artifact@v7
        with:
          name: image-${{ matrix.client }}
      - name: Load docker images
        run: |
          docker load --input quic-network-simulator.tar.gz
          docker load --input quic-interop-iperf-endpoint.tar.gz
          docker load --input ${{ inputs.server }}.tar.gz
          docker load --input ${{ matrix.client }}.tar.gz
      - run: docker image ls
      - name: Install Wireshark
        run: |
          sudo add-apt-repository ppa:wireshark-dev/nightly
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends tshark
      - name: Install Python packages
        run: |
          pip install -U pip
          pip install -r requirements.txt
      - name: Run tests
        env:
          CRON: "true"
        run: |
          (python run.py --client ${{ matrix.client }} --server ${{ inputs.server }} --log-dir logs --json ${{ inputs.server }}_${{ matrix.client }}_results.json -t onlyTests || true) | tee output.txt
          mkdir -p logs/${{ inputs.server }}_${{ matrix.client }}
          mv output.txt logs/${{ inputs.server }}_${{ matrix.client }}/
      - name: Run measurements
        env:
          CRON: "true"
        run: |
          python run.py --client ${{ matrix.client }} --server ${{ inputs.server }} --log-dir logs_measurement --json ${{ inputs.server }}_${{ matrix.client }}_measurements.json -t onlyMeasurements || true
          if [ ! -d "logs_measurement" ]; then exit 0; fi
          find logs_measurement -depth -name "sim" -type d -exec rm -r "{}" \;
          find logs_measurement -depth -name "client" -type d -exec rm -r "{}" \;
          find logs_measurement -depth -name "server" -type d -exec rm -r "{}" \;
          mv logs_measurement/${{ inputs.server }}_${{ matrix.client }}/* logs/${{ inputs.server }}_${{ matrix.client }}/
      - name: Upload logs to interop.seemann.io
        uses: burnett01/rsync-deployments@dc0d5d44c4728aad3f02154a87309809e62a960f # v8.0.4
        if: ${{ always() && github.event_name == 'schedule' }}
        with:
          switches: -avzr --relative
          path: logs/./${{ inputs.server }}_${{ matrix.client }}/
          remote_path: ${{ vars.LOG_DIR }}/${{ inputs.logname }}
          remote_host: interop.seemann.io
          remote_user: ${{ secrets.INTEROP_SEEMANN_IO_USER }}
          remote_key: ${{ secrets.INTEROP_SEEMANN_IO_SSH_KEY }}
      - name: Upload result
        uses: actions/upload-artifact@v6
        with:
          name: results-${{ inputs.server }}-${{ matrix.client }}
          if-no-files-found: error
          path: |
            ${{ inputs.server }}_${{ matrix.client }}_results.json
            ${{ inputs.server }}_${{ matrix.client }}_measurements.json
