name: quic-interop-runner

on:
  pull_request:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build your Docker image.

      - name: Run QUIC Interop tests
        uses: ./
        with:
          name: 'neqo-latest'
          # Replace with the name of the freshly-build local docker image.
          image: 'ghcr.io/mozilla/neqo-qns:latest'
          url: https://github.com/mozilla/neqo
